### ISSUE TITLE
question

### ISSUE THREAD

**Issue by SamanaBS** [vineeths96/Spoken-Keyword-Spotting#11]
why is the OCSVM taking input from the penultimate dense layer of CNN ?

**Comment by vineeths96** [comment]
We use the CNN model as a feature extractor. Since we have trained a model to perform word classification, we expect it to learn rich latent representations. Hence, we pick the output of a dense layer as our feature for OCSVM.

Infact, you can use any layer's output as your feature. You should probably try with different ones. But typically, the deeper the better

**Comment by SamanaBS** [comment]
okay thank
